# Generated by Django 3.2.13 on 2023-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerId', models.CharField(max_length=255)),
                ('encryptedSummonerId', models.CharField(max_length=255)),
                ('puuId', models.CharField(max_length=255)),
            ],
        ),
    ]
