# Generated by Django 3.2.13 on 2023-04-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='summonerLevel',
            field=models.IntegerField(null=True),
        ),
    ]
