# Generated by Django 3.2.13 on 2023-04-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueAPI', '0002_summoner_summonerlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='summonerId',
            new_name='summonerName',
        ),
    ]
